import os
import unittest

from visualize_blueprint import load_blueprint, render_document, render_mermaid

FIXTURES = os.path.join(os.path.dirname(__file__), "fixtures")


class TestRenderDocument(unittest.TestCase):
    def setUp(self):
        self.bp = load_blueprint(os.path.join(FIXTURES, "multi.blueprint.md"))
        self.doc = render_document(self.bp, "multi")

    def test_title_and_sections(self):
        self.assertTrue(self.doc.startswith("# multi — workflow diagram\n"))
        self.assertIn("## Flow", self.doc)
        self.assertIn("## Step details", self.doc)
        self.assertIn("## Subagents", self.doc)

    def test_embeds_mermaid_block(self):
        self.assertIn("```mermaid\n" + render_mermaid(self.bp) + "\n```", self.doc)

    def test_generated_comment_and_caption(self):
        self.assertIn("<!-- Generated by workflow-design-visualize from multi.blueprint.md.", self.doc)
        self.assertIn("no edges are drawn between them", self.doc)

    def test_trailing_newline(self):
        self.assertTrue(self.doc.endswith("\n"))

    def test_deterministic(self):
        self.assertEqual(render_document(self.bp, "multi"), render_document(self.bp, "multi"))


if __name__ == "__main__":
    unittest.main()
